#! /bin/sh

~/code/nixos-config/dotfiles/bspwm/monitor_detect.sh

killall sxhkd
sxhkd &

xsetroot -cursor_name left_ptr

# timesync seems to start only after being queried ???
timedatectl timesync-status &

~/.config/bspwm/desktops.sh

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
# bspc config pointer_follows_focus       true
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config focused_border_color "#c94f6d"

bspc rule -a Thunar state=floating
bspc rule -a Nemo state=floating

bspc rule -a '*:gitk' state=floating
bspc rule -a '*:dialog' state=floating
bspc rule -a '*:simplescreenrecorder' state=floating
bspc rule -a '*:galculator' state=floating
bspc rule -a '*:xfce4-appfinder' state=floating
bspc rule -a '*:.blueman-manager-wrapped' state=floating rectangle=400x800+1380+40 monitor=^1
bspc rule -a "*:.pick-colour-picker-wrapped" state=floating
bspc rule -a "AFFiNE" state=floating

bspc rule -a "*:bitwarden" state=floating rectangle=680x500 center=on
bspc rule -a "*:scratchterm" state=floating rectangle=1600x800+0+0 center=on

bspc config external_rules_command ~/.config/bspwm/external_rules.sh


# ~/.config/polybar/launch.sh &
~/code/nixos-config/dotfiles/polybar/launch.sh &
~/code/nixos-config/dotfiles/bspwm/setwall.sh &
killall volumeicon
volumeicon &
# picom &
# killall udiskie
# udiskie &

if [ "$(hostname)" = "nt-oryx" ]; then
  # eww daemon &
  # eww open sidebar &
  sudo system76-power profile battery
  light -S 60
  sudo sys76-kb set -c purple -b 90
  # sudo dex -a &
  # disable monitor blanking and screensaver
  xset -dpms
  xset s off
  # systemctl --user start rslsync &
fi

~/.config/bspwm/welcome.sh &
echo "rc complete"
