#!/usr/bin/env bash
ids=$(xdotool search --classname scratchterm)

if [ "$ids" != "" ]
then
  # for each id, we need to set the flag hidden
  echo "$ids" | xargs -I{} bspc node {} --flag hidden -f -d $(bspc query -D -d) --follow
else
  # alacritty --class "scratchterm,scratchterm" &
  # wezterm start --class "scratchterm"
  ghostty --x11-instance-name=scratchterm
fi
